/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BotDashboardRouteImport } from './routes/bot-dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientPoolRouteImport } from './routes/client.pool'
import { Route as ClientNewsRouteImport } from './routes/client.news'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as DashboardTestPanelRouteImport } from './routes/_dashboard/test-panel'
import { Route as DashboardNewsRouteImport } from './routes/_dashboard/news'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCreditsRouteImport } from './routes/_dashboard/credits'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard/clients'
import { Route as DashboardBotHealthRouteImport } from './routes/_dashboard/bot-health'
import { Route as DashboardBotControlRouteImport } from './routes/_dashboard/bot-control'
import { Route as DashboardAgentsRouteImport } from './routes/_dashboard/agents'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin'
import { Route as ClientStatsSmsRouteImport } from './routes/client.stats.sms'
import { Route as ClientStatsCdrRouteImport } from './routes/client.stats.cdr'
import { Route as ClientSmsNumbersRouteImport } from './routes/client.sms.numbers'
import { Route as DashboardStatsSmsRouteImport } from './routes/_dashboard/stats/sms'
import { Route as DashboardStatsRangeRouteImport } from './routes/_dashboard/stats/range'
import { Route as DashboardStatsNumberRouteImport } from './routes/_dashboard/stats/number'
import { Route as DashboardStatsClientRouteImport } from './routes/_dashboard/stats/client'
import { Route as DashboardStatsCdrRouteImport } from './routes/_dashboard/stats/cdr'
import { Route as DashboardSmsSyncStatusRouteImport } from './routes/_dashboard/sms/sync-status'
import { Route as DashboardSmsRatecardRouteImport } from './routes/_dashboard/sms/ratecard'
import { Route as DashboardSmsRangesRouteImport } from './routes/_dashboard/sms/ranges'
import { Route as DashboardSmsNumbersRouteImport } from './routes/_dashboard/sms/numbers'
import { Route as DashboardAgentOtpsRouteImport } from './routes/_dashboard/agent/otps'
import { Route as DashboardAgentNumbersRouteImport } from './routes/_dashboard/agent/numbers'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BotDashboardRoute = BotDashboardRouteImport.update({
  id: '/bot-dashboard',
  path: '/bot-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPoolRoute = ClientPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNewsRoute = ClientNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const DashboardTestPanelRoute = DashboardTestPanelRouteImport.update({
  id: '/test-panel',
  path: '/test-panel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBotHealthRoute = DashboardBotHealthRouteImport.update({
  id: '/bot-health',
  path: '/bot-health',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBotControlRoute = DashboardBotControlRouteImport.update({
  id: '/bot-control',
  path: '/bot-control',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ClientStatsSmsRoute = ClientStatsSmsRouteImport.update({
  id: '/stats/sms',
  path: '/stats/sms',
  getParentRoute: () => ClientRoute,
} as any)
const ClientStatsCdrRoute = ClientStatsCdrRouteImport.update({
  id: '/stats/cdr',
  path: '/stats/cdr',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSmsNumbersRoute = ClientSmsNumbersRouteImport.update({
  id: '/sms/numbers',
  path: '/sms/numbers',
  getParentRoute: () => ClientRoute,
} as any)
const DashboardStatsSmsRoute = DashboardStatsSmsRouteImport.update({
  id: '/stats/sms',
  path: '/stats/sms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRangeRoute = DashboardStatsRangeRouteImport.update({
  id: '/stats/range',
  path: '/stats/range',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsNumberRoute = DashboardStatsNumberRouteImport.update({
  id: '/stats/number',
  path: '/stats/number',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsClientRoute = DashboardStatsClientRouteImport.update({
  id: '/stats/client',
  path: '/stats/client',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsCdrRoute = DashboardStatsCdrRouteImport.update({
  id: '/stats/cdr',
  path: '/stats/cdr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsSyncStatusRoute = DashboardSmsSyncStatusRouteImport.update({
  id: '/sms/sync-status',
  path: '/sms/sync-status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsRatecardRoute = DashboardSmsRatecardRouteImport.update({
  id: '/sms/ratecard',
  path: '/sms/ratecard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsRangesRoute = DashboardSmsRangesRouteImport.update({
  id: '/sms/ranges',
  path: '/sms/ranges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsNumbersRoute = DashboardSmsNumbersRouteImport.update({
  id: '/sms/numbers',
  path: '/sms/numbers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentOtpsRoute = DashboardAgentOtpsRouteImport.update({
  id: '/agent/otps',
  path: '/agent/otps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentNumbersRoute = DashboardAgentNumbersRouteImport.update({
  id: '/agent/numbers',
  path: '/agent/numbers',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/bot-dashboard': typeof BotDashboardRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof DashboardAdminRoute
  '/agents': typeof DashboardAgentsRoute
  '/bot-control': typeof DashboardBotControlRoute
  '/bot-health': typeof DashboardBotHealthRoute
  '/clients': typeof DashboardClientsRoute
  '/credits': typeof DashboardCreditsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/news': typeof DashboardNewsRoute
  '/test-panel': typeof DashboardTestPanelRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/news': typeof ClientNewsRoute
  '/client/pool': typeof ClientPoolRoute
  '/agent/numbers': typeof DashboardAgentNumbersRoute
  '/agent/otps': typeof DashboardAgentOtpsRoute
  '/sms/numbers': typeof DashboardSmsNumbersRoute
  '/sms/ranges': typeof DashboardSmsRangesRoute
  '/sms/ratecard': typeof DashboardSmsRatecardRoute
  '/sms/sync-status': typeof DashboardSmsSyncStatusRoute
  '/stats/cdr': typeof DashboardStatsCdrRoute
  '/stats/client': typeof DashboardStatsClientRoute
  '/stats/number': typeof DashboardStatsNumberRoute
  '/stats/range': typeof DashboardStatsRangeRoute
  '/stats/sms': typeof DashboardStatsSmsRoute
  '/client/sms/numbers': typeof ClientSmsNumbersRoute
  '/client/stats/cdr': typeof ClientStatsCdrRoute
  '/client/stats/sms': typeof ClientStatsSmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/bot-dashboard': typeof BotDashboardRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof DashboardAdminRoute
  '/agents': typeof DashboardAgentsRoute
  '/bot-control': typeof DashboardBotControlRoute
  '/bot-health': typeof DashboardBotHealthRoute
  '/clients': typeof DashboardClientsRoute
  '/credits': typeof DashboardCreditsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/news': typeof DashboardNewsRoute
  '/test-panel': typeof DashboardTestPanelRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/news': typeof ClientNewsRoute
  '/client/pool': typeof ClientPoolRoute
  '/agent/numbers': typeof DashboardAgentNumbersRoute
  '/agent/otps': typeof DashboardAgentOtpsRoute
  '/sms/numbers': typeof DashboardSmsNumbersRoute
  '/sms/ranges': typeof DashboardSmsRangesRoute
  '/sms/ratecard': typeof DashboardSmsRatecardRoute
  '/sms/sync-status': typeof DashboardSmsSyncStatusRoute
  '/stats/cdr': typeof DashboardStatsCdrRoute
  '/stats/client': typeof DashboardStatsClientRoute
  '/stats/number': typeof DashboardStatsNumberRoute
  '/stats/range': typeof DashboardStatsRangeRoute
  '/stats/sms': typeof DashboardStatsSmsRoute
  '/client/sms/numbers': typeof ClientSmsNumbersRoute
  '/client/stats/cdr': typeof ClientStatsCdrRoute
  '/client/stats/sms': typeof ClientStatsSmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/bot-dashboard': typeof BotDashboardRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/admin': typeof DashboardAdminRoute
  '/_dashboard/agents': typeof DashboardAgentsRoute
  '/_dashboard/bot-control': typeof DashboardBotControlRoute
  '/_dashboard/bot-health': typeof DashboardBotHealthRoute
  '/_dashboard/clients': typeof DashboardClientsRoute
  '/_dashboard/credits': typeof DashboardCreditsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/news': typeof DashboardNewsRoute
  '/_dashboard/test-panel': typeof DashboardTestPanelRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/news': typeof ClientNewsRoute
  '/client/pool': typeof ClientPoolRoute
  '/_dashboard/agent/numbers': typeof DashboardAgentNumbersRoute
  '/_dashboard/agent/otps': typeof DashboardAgentOtpsRoute
  '/_dashboard/sms/numbers': typeof DashboardSmsNumbersRoute
  '/_dashboard/sms/ranges': typeof DashboardSmsRangesRoute
  '/_dashboard/sms/ratecard': typeof DashboardSmsRatecardRoute
  '/_dashboard/sms/sync-status': typeof DashboardSmsSyncStatusRoute
  '/_dashboard/stats/cdr': typeof DashboardStatsCdrRoute
  '/_dashboard/stats/client': typeof DashboardStatsClientRoute
  '/_dashboard/stats/number': typeof DashboardStatsNumberRoute
  '/_dashboard/stats/range': typeof DashboardStatsRangeRoute
  '/_dashboard/stats/sms': typeof DashboardStatsSmsRoute
  '/client/sms/numbers': typeof ClientSmsNumbersRoute
  '/client/stats/cdr': typeof ClientStatsCdrRoute
  '/client/stats/sms': typeof ClientStatsSmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/bot-dashboard'
    | '/client'
    | '/login'
    | '/register'
    | '/admin'
    | '/agents'
    | '/bot-control'
    | '/bot-health'
    | '/clients'
    | '/credits'
    | '/dashboard'
    | '/news'
    | '/test-panel'
    | '/client/dashboard'
    | '/client/news'
    | '/client/pool'
    | '/agent/numbers'
    | '/agent/otps'
    | '/sms/numbers'
    | '/sms/ranges'
    | '/sms/ratecard'
    | '/sms/sync-status'
    | '/stats/cdr'
    | '/stats/client'
    | '/stats/number'
    | '/stats/range'
    | '/stats/sms'
    | '/client/sms/numbers'
    | '/client/stats/cdr'
    | '/client/stats/sms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/bot-dashboard'
    | '/client'
    | '/login'
    | '/register'
    | '/admin'
    | '/agents'
    | '/bot-control'
    | '/bot-health'
    | '/clients'
    | '/credits'
    | '/dashboard'
    | '/news'
    | '/test-panel'
    | '/client/dashboard'
    | '/client/news'
    | '/client/pool'
    | '/agent/numbers'
    | '/agent/otps'
    | '/sms/numbers'
    | '/sms/ranges'
    | '/sms/ratecard'
    | '/sms/sync-status'
    | '/stats/cdr'
    | '/stats/client'
    | '/stats/number'
    | '/stats/range'
    | '/stats/sms'
    | '/client/sms/numbers'
    | '/client/stats/cdr'
    | '/client/stats/sms'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/admin-login'
    | '/bot-dashboard'
    | '/client'
    | '/login'
    | '/register'
    | '/_dashboard/admin'
    | '/_dashboard/agents'
    | '/_dashboard/bot-control'
    | '/_dashboard/bot-health'
    | '/_dashboard/clients'
    | '/_dashboard/credits'
    | '/_dashboard/dashboard'
    | '/_dashboard/news'
    | '/_dashboard/test-panel'
    | '/client/dashboard'
    | '/client/news'
    | '/client/pool'
    | '/_dashboard/agent/numbers'
    | '/_dashboard/agent/otps'
    | '/_dashboard/sms/numbers'
    | '/_dashboard/sms/ranges'
    | '/_dashboard/sms/ratecard'
    | '/_dashboard/sms/sync-status'
    | '/_dashboard/stats/cdr'
    | '/_dashboard/stats/client'
    | '/_dashboard/stats/number'
    | '/_dashboard/stats/range'
    | '/_dashboard/stats/sms'
    | '/client/sms/numbers'
    | '/client/stats/cdr'
    | '/client/stats/sms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BotDashboardRoute: typeof BotDashboardRoute
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-dashboard': {
      id: '/bot-dashboard'
      path: '/bot-dashboard'
      fullPath: '/bot-dashboard'
      preLoaderRoute: typeof BotDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/pool': {
      id: '/client/pool'
      path: '/pool'
      fullPath: '/client/pool'
      preLoaderRoute: typeof ClientPoolRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/news': {
      id: '/client/news'
      path: '/news'
      fullPath: '/client/news'
      preLoaderRoute: typeof ClientNewsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_dashboard/test-panel': {
      id: '/_dashboard/test-panel'
      path: '/test-panel'
      fullPath: '/test-panel'
      preLoaderRoute: typeof DashboardTestPanelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/news': {
      id: '/_dashboard/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/credits': {
      id: '/_dashboard/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bot-health': {
      id: '/_dashboard/bot-health'
      path: '/bot-health'
      fullPath: '/bot-health'
      preLoaderRoute: typeof DashboardBotHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bot-control': {
      id: '/_dashboard/bot-control'
      path: '/bot-control'
      fullPath: '/bot-control'
      preLoaderRoute: typeof DashboardBotControlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents': {
      id: '/_dashboard/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/client/stats/sms': {
      id: '/client/stats/sms'
      path: '/stats/sms'
      fullPath: '/client/stats/sms'
      preLoaderRoute: typeof ClientStatsSmsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/stats/cdr': {
      id: '/client/stats/cdr'
      path: '/stats/cdr'
      fullPath: '/client/stats/cdr'
      preLoaderRoute: typeof ClientStatsCdrRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/sms/numbers': {
      id: '/client/sms/numbers'
      path: '/sms/numbers'
      fullPath: '/client/sms/numbers'
      preLoaderRoute: typeof ClientSmsNumbersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_dashboard/stats/sms': {
      id: '/_dashboard/stats/sms'
      path: '/stats/sms'
      fullPath: '/stats/sms'
      preLoaderRoute: typeof DashboardStatsSmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stats/range': {
      id: '/_dashboard/stats/range'
      path: '/stats/range'
      fullPath: '/stats/range'
      preLoaderRoute: typeof DashboardStatsRangeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stats/number': {
      id: '/_dashboard/stats/number'
      path: '/stats/number'
      fullPath: '/stats/number'
      preLoaderRoute: typeof DashboardStatsNumberRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stats/client': {
      id: '/_dashboard/stats/client'
      path: '/stats/client'
      fullPath: '/stats/client'
      preLoaderRoute: typeof DashboardStatsClientRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stats/cdr': {
      id: '/_dashboard/stats/cdr'
      path: '/stats/cdr'
      fullPath: '/stats/cdr'
      preLoaderRoute: typeof DashboardStatsCdrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/sync-status': {
      id: '/_dashboard/sms/sync-status'
      path: '/sms/sync-status'
      fullPath: '/sms/sync-status'
      preLoaderRoute: typeof DashboardSmsSyncStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/ratecard': {
      id: '/_dashboard/sms/ratecard'
      path: '/sms/ratecard'
      fullPath: '/sms/ratecard'
      preLoaderRoute: typeof DashboardSmsRatecardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/ranges': {
      id: '/_dashboard/sms/ranges'
      path: '/sms/ranges'
      fullPath: '/sms/ranges'
      preLoaderRoute: typeof DashboardSmsRangesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/numbers': {
      id: '/_dashboard/sms/numbers'
      path: '/sms/numbers'
      fullPath: '/sms/numbers'
      preLoaderRoute: typeof DashboardSmsNumbersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agent/otps': {
      id: '/_dashboard/agent/otps'
      path: '/agent/otps'
      fullPath: '/agent/otps'
      preLoaderRoute: typeof DashboardAgentOtpsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agent/numbers': {
      id: '/_dashboard/agent/numbers'
      path: '/agent/numbers'
      fullPath: '/agent/numbers'
      preLoaderRoute: typeof DashboardAgentNumbersRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardBotControlRoute: typeof DashboardBotControlRoute
  DashboardBotHealthRoute: typeof DashboardBotHealthRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardTestPanelRoute: typeof DashboardTestPanelRoute
  DashboardAgentNumbersRoute: typeof DashboardAgentNumbersRoute
  DashboardAgentOtpsRoute: typeof DashboardAgentOtpsRoute
  DashboardSmsNumbersRoute: typeof DashboardSmsNumbersRoute
  DashboardSmsRangesRoute: typeof DashboardSmsRangesRoute
  DashboardSmsRatecardRoute: typeof DashboardSmsRatecardRoute
  DashboardSmsSyncStatusRoute: typeof DashboardSmsSyncStatusRoute
  DashboardStatsCdrRoute: typeof DashboardStatsCdrRoute
  DashboardStatsClientRoute: typeof DashboardStatsClientRoute
  DashboardStatsNumberRoute: typeof DashboardStatsNumberRoute
  DashboardStatsRangeRoute: typeof DashboardStatsRangeRoute
  DashboardStatsSmsRoute: typeof DashboardStatsSmsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardBotControlRoute: DashboardBotControlRoute,
  DashboardBotHealthRoute: DashboardBotHealthRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardTestPanelRoute: DashboardTestPanelRoute,
  DashboardAgentNumbersRoute: DashboardAgentNumbersRoute,
  DashboardAgentOtpsRoute: DashboardAgentOtpsRoute,
  DashboardSmsNumbersRoute: DashboardSmsNumbersRoute,
  DashboardSmsRangesRoute: DashboardSmsRangesRoute,
  DashboardSmsRatecardRoute: DashboardSmsRatecardRoute,
  DashboardSmsSyncStatusRoute: DashboardSmsSyncStatusRoute,
  DashboardStatsCdrRoute: DashboardStatsCdrRoute,
  DashboardStatsClientRoute: DashboardStatsClientRoute,
  DashboardStatsNumberRoute: DashboardStatsNumberRoute,
  DashboardStatsRangeRoute: DashboardStatsRangeRoute,
  DashboardStatsSmsRoute: DashboardStatsSmsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientNewsRoute: typeof ClientNewsRoute
  ClientPoolRoute: typeof ClientPoolRoute
  ClientSmsNumbersRoute: typeof ClientSmsNumbersRoute
  ClientStatsCdrRoute: typeof ClientStatsCdrRoute
  ClientStatsSmsRoute: typeof ClientStatsSmsRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientNewsRoute: ClientNewsRoute,
  ClientPoolRoute: ClientPoolRoute,
  ClientSmsNumbersRoute: ClientSmsNumbersRoute,
  ClientStatsCdrRoute: ClientStatsCdrRoute,
  ClientStatsSmsRoute: ClientStatsSmsRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BotDashboardRoute: BotDashboardRoute,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
